let
    Fonte = Sql.Database("servidor", "banco", [Query="DECLARE @TIPO VARCHAR(10) = 'ME,PA'; -- Declare and initialize the variable.#(lf)#(lf)SELECT#(lf)    SC5.C5_FILIAL AS FILIAL,#(lf)    SC5.C5_NUM AS PEDIDO,#(lf)    CONVERT(DATE, CAST(SC5.C5_FECENT AS VARCHAR(8)), 112) AS ENTREGA,#(lf)    CONVERT(DATE, CAST(SC5.C5_EMISSAO AS VARCHAR(8)), 112) AS EMISSAO,#(lf)    FAMILIA.ACU_COD AS FAMILIA,#(lf)    LTRIM(RTRIM(FAMILIA.ACU_DESC)) AS FAMILIA_DS,#(lf)    GRUPO.ACU_COD AS GRUPO,#(lf)    LTRIM(RTRIM(GRUPO.ACU_DESC)) AS GRUPO_DS,#(lf)    SB1.B1_COD AS PRODUTO,#(lf)    LTRIM(RTRIM(SB1.B1_DESC)) AS PRODUTO_DS,#(lf)    ISNULL(ACY.ACY_GRPVEN, SA1.A1_COD) AS GRUPO_CLIENTE,#(lf)    LTRIM(RTRIM(ISNULL(ACY.ACY_DESCRI, SA1.A1_NOME))) AS GRUPO_CLIENTE_NOME,#(lf)    SA1.A1_LOJA AS LOJA,#(lf)    SA1.A1_COD AS CLIENTE,#(lf)    LTRIM(RTRIM(SA1.A1_NOME)) AS CLIENTE_NOME,#(lf)    LTRIM(RTRIM(SA1.A1_MUN)) AS MUNICIPIO,#(lf)    LTRIM(RTRIM(SA1.A1_EST)) AS ESTADO,#(lf)    SA1.A1_TCDREG AS REGIAO,#(lf)    LTRIM(RTRIM(ZZ5.ZZ5_REGIAO)) AS REGIAO_DS,#(lf)    SA1.A1_TCDRAMO AS RAMO,#(lf)    LTRIM(RTRIM(ZZ6.ZZ6_DESC)) AS RAMO_DS,#(lf)    SA3.A3_COD AS REPRESENTANTE,#(lf)    LTRIM(RTRIM(SA3.A3_NOME)) AS REPRESENTANTE_NOME,#(lf)    SUP.A3_COD AS SUPERIOR,#(lf)    LTRIM(RTRIM(SUP.A3_NOME)) AS SUPERIOR_NOME,#(lf)    SC6.C6_QTDVEN AS QUANTIDADE_VENDIDO,#(lf)    SC6.C6_VALOR AS VALOR_VENDIDO,#(lf)    (SC6.C6_QTDVEN * SB1.B1_PESO) AS PESO_VENDIDO,#(lf)    CASE SC5.C5_BLQANTE #(lf)        WHEN 'S' THEN 'BLOQUEADO'#(lf)        WHEN 'A' THEN 'APROVADO'#(lf)        WHEN 'R' THEN 'REJEITADO'#(lf)        WHEN 'N' THEN 'SEM BLOQUEIO'#(lf)        ELSE '' #(lf)        END AS BLOQUEIO_ANTECIPACAO#(lf)    ,CASE SC5.C5_TOPERP#(lf)        WHEN 01 THEN 'Venda'#(lf)        WHEN 10 THEN 'Bonificação'#(lf)        ELSE 'Sem descrição'#(lf)        END AS TPPED#(lf)    ,C5_XDTCARG AS DT_PRE_CARGA#(lf)    ,C5_XCARGA AS PRE_CARGA#(lf)    ,CASE C5_TPFRETE#(lf)        WHEN 'C' THEN 'CIF'#(lf)        WHEN 'F' THEN 'FOB'#(lf)        WHEN 'T' THEN 'TERCEIROS'#(lf)        WHEN 'R' THEN 'REMETENTE'#(lf)        WHEN 'D' THEN 'DESTINATÁRIO'#(lf)        WHEN 'S' THEN 'SEM FRETE'#(lf)        ELSE 'NÃO IDENTIFICADO'#(lf)        END AS 'FRETE'#(lf)FROM#(lf)    SC5010 SC5 WITH(NOLOCK)#(lf)INNER JOIN SC6010 SC6 WITH(NOLOCK) ON#(lf)    SC5.C5_FILIAL = SC6.C6_FILIAL#(lf)    AND SC5.C5_NUM = SC6.C6_NUM#(lf)    AND SC6.D_E_L_E_T_ = ''#(lf)INNER JOIN SB1010 SB1 WITH(NOLOCK) ON#(lf)    SB1.B1_FILIAL = SC6.C6_FILIAL#(lf)    AND SB1.B1_COD = SC6.C6_PRODUTO#(lf)    AND SB1.D_E_L_E_T_ = ''#(lf)INNER JOIN SA1010 SA1 WITH(NOLOCK) ON#(lf)    SA1.A1_COD = SC5.C5_CLIENTE#(lf)    AND SA1.A1_LOJA = SC5.C5_LOJACLI#(lf)    AND SA1.D_E_L_E_T_ = ''#(lf)INNER JOIN SA3010 SA3 WITH(NOLOCK) ON#(lf)    SA3.A3_COD = SC5.C5_VEND1#(lf)    AND SA3.D_E_L_E_T_ = ''#(lf)INNER JOIN ZZ5010 ZZ5 WITH(NOLOCK) ON#(lf)    ZZ5.ZZ5_COD = SA1.A1_TCDREG#(lf)    AND ZZ5.D_E_L_E_T_ = ''#(lf)INNER JOIN ZZ6010 ZZ6 WITH(NOLOCK) ON#(lf)    ZZ6.ZZ6_COD = SA1.A1_TCDRAMO#(lf)    AND ZZ6.D_E_L_E_T_ = ''#(lf)INNER JOIN SA3010 SUP WITH(NOLOCK) ON#(lf)    SUP.A3_COD = SA3.A3_SUPER#(lf)    AND SUP.D_E_L_E_T_ = ''#(lf)INNER JOIN ACV010 ACV WITH(NOLOCK) ON#(lf)    ACV.ACV_CODPRO = SB1.B1_COD#(lf)    AND ACV.D_E_L_E_T_ = ''#(lf)    AND ACV.ACV_FILIAL = SUBSTRING(SB1.B1_FILIAL, 1, 4)#(lf)INNER JOIN ACU010 GRUPO WITH(NOLOCK) ON#(lf)    GRUPO.ACU_COD = ACV.ACV_CATEGO#(lf)    AND GRUPO.ACU_FILIAL = ACV.ACV_FILIAL#(lf)    AND GRUPO.D_E_L_E_T_ = ''#(lf)INNER JOIN ACU010 FAMILIA WITH(NOLOCK) ON#(lf)    FAMILIA.ACU_COD = GRUPO.ACU_CODPAI#(lf)    AND FAMILIA.ACU_FILIAL = GRUPO.ACU_FILIAL#(lf)    AND FAMILIA.D_E_L_E_T_ = ''#(lf)LEFT JOIN ACY010 ACY WITH(NOLOCK) ON#(lf)    ACY.ACY_GRPVEN = SA1.A1_GRPVEN#(lf)    AND ACY.D_E_L_E_T_ = ''#(lf)    AND ACY.ACY_FILIAL = '0101'#(lf)WHERE#(lf)    SC5.D_E_L_E_T_ = ''#(lf)    AND SC5.C5_NOTA = ''#(lf)    AND SC6.C6_NOTA = ''#(lf)    --AND SC5.C5_EMISSAO > '20250915'#(lf)    AND CHARINDEX(',' + CAST(SB1.B1_TIPO AS VARCHAR) + ',', ',' + @TIPO + ',') > 0#(lf)    --AND SC5.C5_FECENT < DATEADD(DAY, 2, GETDATE())#(lf)ORDER BY#(lf)   1,23"]),
    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"ENTREGA", type date}, {"EMISSAO", type date}, {"VALOR_VENDIDO", Currency.Type}, {"SUPERIOR", type number}, {"REPRESENTANTE", Int64.Type}, {"QUANTIDADE_VENDIDO", Int64.Type}, {"RAMO", Int64.Type}, {"REGIAO", Int64.Type}, {"CLIENTE", Int64.Type}, {"LOJA", Int64.Type}}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Tipo Alterado",{"FILIAL", "PEDIDO", "ENTREGA", "EMISSAO", "FAMILIA", "FAMILIA_DS", "GRUPO", "GRUPO_DS", "PRODUTO", "PRODUTO_DS", "GRUPO_CLIENTE", "GRUPO_CLIENTE_NOME", "CLIENTE", "LOJA", "CLIENTE_NOME", "MUNICIPIO", "ESTADO", "REGIAO", "REGIAO_DS", "RAMO", "RAMO_DS", "REPRESENTANTE", "REPRESENTANTE_NOME", "SUPERIOR", "SUPERIOR_NOME", "QUANTIDADE_VENDIDO", "VALOR_VENDIDO", "PESO_VENDIDO", "BLOQUEIO_ANTECIPACAO", "TPPED"}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Reordenadas",{{"GRUPO_CLIENTE", Int64.Type}, {"PRODUTO", Int64.Type}, {"GRUPO", Int64.Type}, {"FAMILIA", Int64.Type}}),
    #"Idade Inserida" = Table.AddColumn(#"Tipo Alterado1", "Idade", each Date.From(DateTime.LocalNow()) - [EMISSAO], type duration),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Idade Inserida",{{"Idade", Int64.Type}}),
    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado2",{{"Idade", Order.Descending}}),
    #"Idade Inserida1" = Table.AddColumn(#"Linhas Classificadas", "Idade.1", each Date.From(DateTime.LocalNow()) - [ENTREGA], type duration),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Idade Inserida1",{{"Idade.1", Int64.Type}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado3",{{"Idade.1", "ENTREGA EM"}, {"Idade", "EMISSÃO HÁ"}}),
    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"PRODUTO", Int64.Type}}),
    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado4", {"PRODUTO"}, QUADRO_GERAL_ESTOQUE, {"COD_PRODUTO"}, "QUADRO_GERAL_ESTOQUE", JoinKind.LeftOuter),
    #"QUADRO_GERAL_ESTOQUE Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "QUADRO_GERAL_ESTOQUE", {"PALETE", "TOTAL"}, {"QUADRO_GERAL_ESTOQUE.PALETE", "QUADRO_GERAL_ESTOQUE.TOTAL"}),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"QUADRO_GERAL_ESTOQUE Expandido",{{"QUADRO_GERAL_ESTOQUE.PALETE", "PALETE"}, {"QUADRO_GERAL_ESTOQUE.TOTAL", "ESTOQUE"}}),
    #"Consultas Mescladas1" = Table.NestedJoin(#"Colunas Renomeadas1", {"MUNICIPIO"}, KM, {"CIDADE"}, "KM", JoinKind.LeftOuter),
    #"KM Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "KM", {"DISTÂNCIA 1 VCA", "DISTÂNCIA 2 FS"}, {"KM.DISTÂNCIA 1 VCA", "KM.DISTÂNCIA 2 FS"}),
    #"Valor Substituído" = Table.ReplaceValue(#"KM Expandido",null,0,Replacer.ReplaceValue,{"ESTOQUE"}),
    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Valor Substituído", "SALDO", each if [ESTOQUE] > 0 then "COM SALDO" else "SEM SALDO"),
    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "AGENDAMENTO", each if [RAMO_DS] = "CASH" then "AGENDAMENTO OBRIGATÓRIO" else if [REGIAO_DS] = "DISTRIBUIDOR" then "AGENDAMENTO OBRIGATÓRIO" else "SEM AGENDAMENTO"),
    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Coluna Condicional Adicionada1", "RCA", each Text.Combine({Text.From([REPRESENTANTE], "pt-BR"), [REPRESENTANTE_NOME]}, " "), type text),
    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Coluna Mesclada Inserida", "PRE ANALISE DE STATUS", each if [PRE_CARGA] <> "      " then "Faturável" else if [SALDO] = "SEM SALDO" then "Aguardando Produção" else if [ENTREGA EM] > 5 then "Data Futura" else if [FRETE] = "FOB" then "Cliente Vai Retirar" else if [AGENDAMENTO] = "AGENDAMENTO OBRIGATÓRIO" then "Agendado" else "Aguardando Comercial"),
    #"Coluna Condicional Adicionada3" = Table.AddColumn(#"Coluna Condicional Adicionada2", "DIAS DE ENTREGA", each if [ENTREGA EM] > 5 then "Após 5 Dias" else if [ENTREGA EM] = 0 then "Hoje" else if [ENTREGA EM] >= 1 then "Próximos 5 Dias" else "Últimos Dias"),
    #"Valor Substituído1" = Table.ReplaceValue(#"Coluna Condicional Adicionada3",null,0,Replacer.ReplaceValue,{"KM.DISTÂNCIA 1 VCA", "KM.DISTÂNCIA 2 FS"}),
    #"Coluna Condicional Adicionada4" = Table.AddColumn(#"Valor Substituído1", "ORIGEM INDICADA", each if [KM.DISTÂNCIA 2 FS] < [KM.DISTÂNCIA 1 VCA] then "Filial" else if [KM.DISTÂNCIA 2 FS] > [KM.DISTÂNCIA 1 VCA] then "Matriz" else "S/ Dados"),
    #"Linhas Agrupadas" = Table.Group(#"Coluna Condicional Adicionada4", {"RCA", "PRODUTO", "PRODUTO_DS"}, {{"Qnt", each List.Sum([QUANTIDADE_VENDIDO]), type nullable number}, {"Paletes", each List.Max([PALETE]), type nullable number}, {"Peso", each List.Sum([PESO_VENDIDO]), type number}, {"KM MATRIZ", each List.Max([KM.DISTÂNCIA 1 VCA]), type nullable number}, {"KM FILIAL", each List.Max([KM.DISTÂNCIA 2 FS]), type nullable number}, {"Valor", each List.Sum([VALOR_VENDIDO]), type nullable number}}),
    #"Coluna Condicional Adicionada6" = Table.AddColumn(#"Linhas Agrupadas", "PALETE", each if [PRODUTO] = 1050040003 then 84 else if [PRODUTO] = 2000300001 then 192 else if [PRODUTO] = 2000700001 then 104 else if [PRODUTO] = 2001000006 then 60 else if [PRODUTO] = 2000500001 then 80 else if [PRODUTO] = 2000000004 then 225 else if [PRODUTO] = 2000000001 then 225 else if [PRODUTO] = 2000000002 then 225 else if [PRODUTO] = 2000000003 then 225 else if [PRODUTO] = 2001000010 then 60 else if [PRODUTO] = 2001000009 then 60 else if [PRODUTO] = 2001000007 then 60 else if [PRODUTO] = 2001000008 then 60 else if [PRODUTO] = 1091000001 then 40 else [Paletes]),
    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Condicional Adicionada6", "Paletização", each [Qnt]/[PALETE]),
    #"Linhas Agrupadas1" = Table.Group(#"Personalização Adicionada", {"RCA"}, {{"PESO", each List.Sum([Peso]), type number}, {"QNT", each List.Sum([Qnt]), type nullable number}, {"VALOR", each List.Sum([Valor]), type nullable number}, {"PALETIZAÇÃO", each List.Sum([Paletização]), type number}, {"KM DISTANCIA - MATRIZ", each List.Max([KM MATRIZ]), type nullable number}, {"KM DISTANCIA - FILIAL", each List.Max([KM FILIAL]), type nullable number}}),
    #"Coluna Condicional Adicionada5" = Table.AddColumn(#"Linhas Agrupadas1", "SAÍDA IDEAL", each if [#"KM DISTANCIA - MATRIZ"] > [#"KM DISTANCIA - FILIAL"] then "FILIAL" else if [#"KM DISTANCIA - MATRIZ"] = [#"KM DISTANCIA - FILIAL"] then "Sem dados" else "MATRIZ"),
    #"Coluna Condicional Adicionada7" = Table.AddColumn(#"Coluna Condicional Adicionada5", "KM INDICADO", each if [#"KM DISTANCIA - MATRIZ"] > [#"KM DISTANCIA - FILIAL"] then [#"KM DISTANCIA - FILIAL"] else [#"KM DISTANCIA - MATRIZ"]),
    #"Personalização Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada7", "Nº VEICULOS", each if [PALETIZAÇÃO] >= 30 then [PALETIZAÇÃO]/30
else if [PALETIZAÇÃO] = null then 0
else if [PALETIZAÇÃO] < 1 then 0
else if [PALETIZAÇÃO] >= 1 then 1
else 0),
    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Nº VEICULOS", Int64.Type}}),
    #"Personalização Adicionada2" = Table.AddColumn(#"Tipo Alterado5", "VEICULO", each if [PESO] < 9000 and [KM INDICADO] <= 300
    then "Falta Compl/ TOCO"
else if [PESO] >= 9000 and [PALETIZAÇÃO] <= 12 and [KM INDICADO] <= 300
    then "TOCO"
else if [PESO] < 14000 and [KM INDICADO] > 300
    then "Falta Compl/ TRUCK"
else if [PESO] >= 9000 and [PALETIZAÇÃO] <= 12 and [KM INDICADO] > 300
    then "Falta Compl/ TRUCK"
else if [PESO] >= 14000 and [PALETIZAÇÃO] <= 16
    then "TRUCK"
else if [PESO] >= 170000 and [PALETIZAÇÃO] <= 20
    then "BITRUCK"
else if [PESO] <= 30000 and [PALETIZAÇÃO] <= 30
    then "CARRETA"
else if [PESO] > 30000 and [PALETIZAÇÃO] > 30
    then "CARRETA"
else
    "CARRETA"),
    #"Tipo Alterado6" = Table.TransformColumnTypes(#"Personalização Adicionada2",{{"PALETIZAÇÃO", type number}}),
    Arredondado = Table.TransformColumns(#"Tipo Alterado6",{{"PALETIZAÇÃO", each Number.Round(_, 2), type number}}),
    #"Colunas Renomeadas2" = Table.RenameColumns(Arredondado,{{"KM DISTANCIA - MATRIZ", "KM MATRIZ"}, {"KM DISTANCIA - FILIAL", "KM FILIAL"}})
in
    #"Colunas Renomeadas2"
