let
    Fonte = Sql.Database("189.126.154.173,2372", "CRU3L2_163582_PR_PD", [Query="DECLARE @DataInicial VARCHAR(8) = CONVERT(VARCHAR(8), DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1), 112)#(lf)DECLARE @DataFinal   VARCHAR(8) = CONVERT(VARCHAR(8), GETDATE(), 112);#(lf)#(lf)WITH BASESB2 AS( #(lf)#(lf)SELECT #(lf)    SB2.B2_COD,#(lf)    SB2.B2_FILIAL,#(lf)    SB2.B2_LOCAL,#(lf)    SB2.B2_QATU#(lf)  #(lf)FROM#(lf)    SB2010 AS SB2#(lf)   #(lf)    WHERE#(lf)    SB2.D_E_L_E_T_ = ''#(lf)    AND SB2.B2_LOCAL IN ('54','12','80','55')#(lf)    AND SB2.B2_USAI BETWEEN '000000' AND @DataFinal#(lf)    AND SB2.B2_FILIAL IN ('010101','010102')#(lf)    )#(lf)#(lf)    SELECT #(lf)        SB1.B1_COD,#(lf)        SB1.B1_DESC,#(lf)        SB1.B1_TIPO,#(lf)        CASE#(lf)        WHEN B1_COD IN ('1020000007','1020000007','1020000009','1020000009','1020550001','1020550001','1020560001','1020560001','1020170001','1020170001','1020170005','1020170005','1020180001','1020180001','1020170003','1020170003','1020170007','1020170007','1020180003','1020180003','1020170002','1020170002','1020170006','1020170006','1020180002','1020180002','1020170004','1020170004','1020170008','1020170008','1020180004','1020180004','1020440005','1020440005','1020440004','1020440004','1020440003','1020440003','1020440002','1020440002','1020440001','1020440001','1020210001','1020210001','1020210002','1020210002','1000330003','1000330003','1000330001','1000330001','1000330002','1000330002') #(lf)        THEN 'ATILA'#(lf)#(lf)        WHEN B1_COD IN ('1110000002','1110000002') #(lf)        THEN 'BRASAGEL'#(lf)#(lf)        WHEN B1_COD IN ('1020000008','1020000008','1050030001','1050030001','1020710002','1020710002','1020710001','1020710001') #(lf)        THEN 'EKOBOM'#(lf)#(lf)        WHEN B1_COD IN ('1091000001','1090000004','1091000001','1090000001','1090000001','1091000002','1091000002','1090000002','1090000002','1010000006','1010000006','1010000009','1010000009','1010000007','1010000007','1010000010','1010000008','1010000012','1010000012','1010000011','1010000011','1010000004','1010000004','1010010004','1010010004','1010000016','1010000016','1010010001','1010010001','1010000001','1010000001','1010000014','1010000014','1010000005','1010000005','1010010005','1010010005','1010000017','1010000017','1010000003','1010000003','1010010003','1010010003','1010000013','1010000013','1010000002','1010000002','1010010002','1010010002','1010000015','1010000015') #(lf)        THEN 'MARAN'#(lf)#(lf)        WHEN B1_COD IN ('1020000004','1020000004') #(lf)        THEN 'MEIRA'#(lf)#(lf)        WHEN B1_COD IN ('1100000001','1100000001','1100000002','1100000002') #(lf)        THEN 'MR BLUE'#(lf)#(lf)        WHEN B1_COD IN ('1020000002','1020000002','1020420002','1020420002','1020420001','1020420001','1000100007','1000100007','1000100006','1000100006','1000100001','1000100001','1000100005','1000100005','1000100008','1000100008','1000100003','1000100004','1000100004','1000100003','1000100002','1000100002') #(lf)        THEN 'RIO BAHIA'#(lf)#(lf)        WHEN B1_COD IN ('1000200001','1000200001','1000200002','1000200002') #(lf)        THEN 'RITMO'#(lf)#(lf)        WHEN B1_COD IN ('1050040002','1050040002','1050040003','1050040003','1050040001','1050040001','1200000002','1200000002','1200000003','1200000003','1200000001','1200000001','1020720002','1020720002','1020720005','1020720005','1020730001','1020720006','1020720006','1020720003','1020720003','1020720004','1020720004','1020720001','1020720001','1020730003','1020730003','1020730004','1020730004','2000800001','1020730002','1020730002') #(lf)        THEN 'VATZ'#(lf)#(lf)        ELSE 'TEIU'#(lf)    END AS MARCA,#(lf)        CASE#(lf)            WHEN SB1.B1_GRUPO IN ('102000')#(lf)            THEN 'AGUA'#(lf)        #(lf)            WHEN SB1.B1_GRUPO IN ('102040', '102043', '102041', '102042', '102044') #(lf)            THEN 'DETERGENTE'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('101000','101001') #(lf)            THEN 'SABONETE EM BARRA'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('100000','100010','100020','100030','100031','100032','100033','100040') #(lf)            THEN 'SABÃO'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('111000') #(lf)            THEN 'ALCOOL'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('102030','102031')#(lf)            THEN 'ALVEJANTE'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('102051','102052','102054','102050','102053','102055','102056') #(lf)            THEN 'AMACIANTE'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('102010','102011','102012','102013','102014','102015','102016','102017','102018') #(lf)            THEN 'DESINFETANTE'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('104000') #(lf)            THEN 'ESPONJA'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('102020','102021') #(lf)            THEN 'GEL MULTIUSO'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('200110','106000') #(lf)            THEN 'LA DE ACO'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('102060','102061','102062','102063','102064','102065') #(lf)            THEN 'LAVA ROUPAS'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('105002','105003','105004') #(lf)            THEN 'LIMPA VIDROS'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('105000','105001','120000') #(lf)            THEN 'LIMPADOR'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('102070','102071','102072')#(lf)            THEN 'MULTIUSO'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('109100','109000') #(lf)            THEN 'SABONETE EM LIQUIDO'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('102073') #(lf)            THEN 'TIRA LIMO'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('200000') #(lf)            THEN 'SACO DE LIXO'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('103000')#(lf)            THEN 'VELA'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('200010')#(lf)            THEN 'ODORIZADOR'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('200030')#(lf)            THEN 'INSETICIDA'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('200040','200041')#(lf)            THEN 'VASSOURA'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('200050')#(lf)            THEN 'PA'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('200060')#(lf)            THEN 'RODO' #(lf)        #(lf)            WHEN SB1.B1_GRUPO IN ('200070')#(lf)            THEN 'ESCOVA'#(lf)#(lf)            WHEN SB1.B1_GRUPO IN ('200100')#(lf)            THEN 'PEDRA SANITÁRIA'#(lf)#(lf)            ELSE 'TERCERIZADO'#(lf)            END AS 'FAMILIA',#(lf)   #(lf)      SB1.B1_TIPO,#(lf)      SB1.B1_PESBRU,#(lf)      CASE SB1.B1_COD#(lf)            WHEN '1050040003' THEN '84'#(lf)            WHEN '2000300001' THEN '192'#(lf)            WHEN '2000700001' THEN '104'#(lf)            WHEN '2000500001' THEN '80'#(lf)            WHEN '1091000001' THEN '40'#(lf)            WHEN '2000000004' THEN '225'#(lf)            WHEN '2000000001' THEN '225'#(lf)            WHEN '2000000002' THEN '225'#(lf)            WHEN '2000000003' THEN '225'#(lf)            WHEN '2001000006' THEN '60'#(lf)            WHEN '2001000010' THEN '60'#(lf)            WHEN '2001000009' THEN '60'#(lf)            WHEN '2001000007' THEN '60'#(lf)            WHEN '2001000008' THEN '60'#(lf)            ELSE SB1.B1_TQPAL#(lf)END AS B1_TQPAL,#(lf)      SB1.B1_UM,#(lf)      SB2.B2_FILIAL,#(lf)      SB2.B2_LOCAL,#(lf)      SB2.B2_QATU  #(lf)#(lf)    FROM BASESB2 SB2#(lf)    INNER JOIN SB1010 AS SB1#(lf)ON#(lf)    SB2.B2_COD = SB1.B1_COD#(lf)    AND SB1.D_E_L_E_T_ = ''#(lf)    AND SB1.B1_FILIAL = '010101'#(lf)    AND SB1.B1_TIPO IN ('ME','PA')"]),
    #"Coluna Duplicada" = Table.DuplicateColumn(Fonte, "B2_QATU", "B2_QATU - Copiar"),
    #"Coluna em pivô" = Table.Pivot(#"Coluna Duplicada", List.Distinct(#"Coluna Duplicada"[B2_FILIAL]), "B2_FILIAL", "B2_QATU - Copiar", List.Sum),
    #"Coluna em pivô1" = Table.Pivot(#"Coluna em pivô", List.Distinct(#"Coluna em pivô"[B2_LOCAL]), "B2_LOCAL", "B2_QATU", List.Sum),
    #"Linhas Agrupadas" = Table.Group(#"Coluna em pivô1", {"B1_COD", "B1_DESC", "B1_TIPO","FAMILIA","MARCA"}, {
        {"ETQ01", each List.Sum(try [010101] otherwise {}), type nullable number}, 
        {"ETQ02", each List.Sum(try [010102] otherwise {}), type nullable number}, 
        {"ETQ12", each List.Sum(try [12] otherwise {}), type nullable number}, 
        {"ETQ80", each List.Sum(try [80] otherwise {}), type nullable number}, 
        {"ETQ54", each List.Sum(try [54] otherwise {}), type nullable number}, 
        {"ETQ55", each List.Sum(try [55] otherwise {}), type nullable number},
        {"PESO", each List.Max([B1_PESBRU]), type number}, 
        {"PALETE", each List.Max([B1_TQPAL]), type number}
    }),
    #"Valor Substituído" = Table.ReplaceValue(#"Linhas Agrupadas",null,0,Replacer.ReplaceValue,{"ETQ01", "ETQ02", "ETQ12", "ETQ80", "ETQ54","ETQ55"}),
    
    #"Colunas Renomeadas" = Table.RenameColumns(#"Valor Substituído",{{"B1_DESC", "PRODUTO"}, {"B1_COD", "COD_PRODUTO"}, {"B1_TIPO", "TIPO"}}),
    
    #"Soma Inserida" = Table.AddColumn(#"Colunas Renomeadas", "Adição", each [ETQ54] + [ETQ80] + [ETQ12], Int64.Type),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Soma Inserida",{{"Adição", "TOTAL"}}),
    
    // ATENÇÃO: COD_PRODUTO mantido como Int64.Type
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"COD_PRODUTO", Int64.Type}}),
    
    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado1", each ([TIPO] = "ME" or [TIPO] = "PA")),
    
    // SALDO MATRIZ e SALDO FILIAL serão automaticamente do tipo Text devido aos valores de retorno "SEM SALDO" e "COM SALDO"
    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas Filtradas", "SALDO MATRIZ", each if [ETQ01] = 0 then "SEM SALDO" else "COM SALDO", Text.Type),
    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "SALDO FILIAL", each if [ETQ02] = 0 then "SEM SALDO" else "COM SALDO", Text.Type),
    #"Linhas Classificadas" = Table.Sort(#"Coluna Condicional Adicionada1",{{"COD_PRODUTO", Order.Ascending}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas Classificadas",{{"SALDO MATRIZ", type text}, {"SALDO FILIAL", type text}, {"COD_PRODUTO", Int64.Type}})
in
    #"Tipo Alterado"
